- name: Prepare OS
  hosts: grp_vbox
  become: yes
  gather_facts: no
  tasks:
    - name: facts
      ansible.builtin.include_tasks: tasks/os_prepare/VboxGetFact.yml
#    - name: install guest additions
#      ansible.builtin.include_tasks: tasks/os_prepare/VboxGuestAdditionInstall.yml
    - name: system
      ansible.builtin.include_tasks: tasks/os_prepare/system.yml
    - name: users
      ansible.builtin.include_tasks: tasks/os_prepare/users.yml
