---
all:
  children:
    vbox:
      children:
         grp_vbox:
           hosts:
             acc-1:
               ansible_host: localhost
               ansible_port: 2222
               ansible_user: ubuntu
               ansible_password: "{{ ubuntu_usr_pwd }}"
               # ansible_become_user: ubuntu
               ansible_become_password: "{{ ubuntu_usr_pwd }}"
               # ansible_ssh_private_key_file:  ~/.ssh/gh_pic16f874_ed25519
               # ansible_host_key_checking: false
             acc-2:
               ansible_host: localhost
               ansible_port: 2223
               ansible_user: ubuntu
               ansible_password: "{{ ubuntu_usr_pwd }}"
               # ansible_ssh_private_key_file:  ~/.ssh/gh_pic16f874_ed25519
