---
all:
  children:
    vbox:
      children:
         grp_vbox:
           hosts:
             XU2404:
#               ansible_port: 2222
#               ansible_user: ubuntu
#               ansible_password: "{{ ubuntu_usr_pwd }}"
#               # ansible_become_user: ubuntu
#               ansible_become_password: "{{ ubuntu_usr_pwd }}"
#               # ansible_ssh_private_key_file:  ~/.ssh/gh_pic16f874_ed25519
#               # ansible_host_key_checking: false
             XU2404-11:
             XU2404-12:
             XU2404-13:
             XU2404-14:
             XU2404-15:
             XU2404-16:
             XU2404-17:
             XU2404-18:
